// Code generated by go generate; DO NOT EDIT.
// This file was generated at: 2021-01-12 22:12:44.279738334 -0800 PST m=+0.000444760
// This file is in sync with: 029723811a36c91f54b901bdd8c7b5467e92071a
package main

// PROGRAM is the human readable product name
const PROGRAM = "number-place"

// VERSION is the human readable product version
const VERSION = "v0.1"
