// Code generated by go generate; DO NOT EDIT.
// This file was generated at: 2021-01-12 19:16:04.70194496 -0800 PST m=+0.000447316
// This file is in sync with: a047f05cbf81d581f56b7d3e59e7e71e3c9e538d
package main

// PROGRAM is the human readable product name
const PROGRAM = "number-place"

// VERSION is the human readable product version
const VERSION = "7102932"
