// Code generated by go generate; DO NOT EDIT.
// This file was generated at: 2021-01-13 15:15:32.003756706 -0800 PST m=+0.000630519
// This file is in sync with: unknown-commit
package main

// PROGRAM is the human readable product name
const PROGRAM = "number-place"

// VERSION is the human readable product version
const VERSION = "v0.1-4-g40e82c9"
