// Code generated by go generate; DO NOT EDIT.
// This file was generated at: 2021-01-18 19:28:57.429949896 -0800 PST m=+0.000514510
// This file is in sync with: unknown-commit
package main

// PROGRAM is the human readable product name
const PROGRAM = "number-place"

// VERSION is the human readable product version
const VERSION = "v0.1-60-g9c096c4"
