// Code generated by go generate; DO NOT EDIT.
// This file was generated at: 2021-01-20 07:00:41.588471632 -0800 PST m=+0.000893210
// This file is in sync with: unknown-commit
package main

// PROGRAM is the human readable product name
const PROGRAM = "number-place"

// VERSION is the human readable product version
const VERSION = "v0.1-80-g1b25237"
